import {
  IconAward,
  IconBoxMultiple,
  IconPoint,
  IconAlertCircle,
  IconNotes,
  IconCalendar,
  IconMail,
  IconTicket,
  IconEdit,
  IconGitMerge,
  IconCurrencyDollar,
  IconApps,
  IconFileDescription,
  IconFileDots,
  IconFiles,
  IconBan,
  IconStar,
  IconMoodSmile,
  IconBorderAll,
  IconBorderHorizontal,
  IconBorderInner,
  IconBorderVertical,
  IconBorderTop,
  IconUserCircle,
  IconPackage,
  IconMessage2,
  IconBasket,
  IconChartLine,
  IconChartArcs,
  IconChartCandle,
  IconChartArea,
  IconChartDots,
  IconChartDonut3,
  IconChartRadar,
  IconLogin,
  IconUserPlus,
  IconRotate,
  IconBox,
  IconAperture,
  IconShoppingCart,
  IconHelp,
  IconBoxAlignBottom,
  IconBoxAlignLeft,
  IconLayout,
  IconZoomCode,
  IconSettings,
  IconBorderStyle2,
  IconAppWindow,
  IconLockAccess,
  IconUser,
  IconReceipt,
  IconCurrencyDollarCanadian,
  IconBrandMastercard,
  IconTransferIn,
  IconDatabase,
} from '@tabler/icons';

import { uniqueId } from 'lodash';

const Menuitems = [
  {
    navlabel: true,
    subheader: 'Fmcg',
  },
  {
    id: uniqueId(),
    title: 'Account Master',
    icon: IconUser,
    href: '/account-master',
  },
  {
    id: uniqueId(),
    title: 'Invoicing',
    icon: IconReceipt,
    href: '/invoicing',
  },
  {
    id: uniqueId(),
    title: 'Cash Receipt',
    icon: IconCurrencyDollarCanadian,
    href: '/cash-receipts',
  },
  {
    id: uniqueId(),
    title: 'Cash Payments',
    icon: IconBrandMastercard,
    href: '/cash-payments',
  },
  {
    id: uniqueId(),
    title: 'Godown Transfer',
    icon: IconTransferIn,
    href: '/godown',
  },
  {
    id: uniqueId(),
    title: 'DBF READER',
    icon: IconDatabase,
    href: '/dbf',
  },
  {
    id: uniqueId(),
    title: 'Add User',
    icon: IconDatabase,
    href: '/adduser',
  },
  {
    id: uniqueId(),
    title: 'Database',
    icon: IconChartDonut3,
    href: '/db/',
    children: [
      {
        id: uniqueId(),
        title: 'Account Master',
        icon: IconUser,
        href: '/db/account-master',
      },
      {
        id: uniqueId(),
        title: 'Invoicing',
        icon: IconReceipt,
        href: '/db/invoicing',
      },
      {
        id: uniqueId(),
        title: 'Cash Receipt',
        icon: IconCurrencyDollarCanadian,
        href: '/db/cash-receipts',
      },
      {
        id: uniqueId(),
        title: 'Cash Payments',
        icon: IconBrandMastercard,
        href: '/db/cash-payments',
      },
      {
        id: uniqueId(),
        title: 'Godown Transfer',
        icon: IconTransferIn,
        href: '/db/godown',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Approved',
    icon: IconChartDonut3,
    href: '/approved/',
    children: [
      {
        id: uniqueId(),
        title: 'Account Master',
        icon: IconUser,
        href: '/approved/account-master',
      },
      {
        id: uniqueId(),
        title: 'Invoicing',
        icon: IconReceipt,
        href: '/approved/invoicing',
      },
      {
        id: uniqueId(),
        title: 'Cash Receipt',
        icon: IconCurrencyDollarCanadian,
        href: '/approved/cash-receipts',
      },
      {
        id: uniqueId(),
        title: 'Cash Payments',
        icon: IconBrandMastercard,
        href: '/approved/cash-payments',
      },
      {
        id: uniqueId(),
        title: 'Godown Transfer',
        icon: IconTransferIn,
        href: '/approved/godown',
      },
    ],
  },


  
];

export default Menuitems;
